-- Skema Tabel visitor_logs untuk Supabase
-- Buat tabel ini di Supabase Dashboard -> SQL Editor

CREATE TABLE IF NOT EXISTS public.visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    nip TEXT,
    nama TEXT,
    role TEXT,
    activity_type TEXT, -- 'login' atau 'page_visit'
    page_name TEXT,
    CONSTRAINT visitor_logs_pkey PRIMARY KEY (id)
);

-- Aktifkan Row Level Security (RLS)
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS (opsional, untuk keamanan)
-- Misal: Izinkan semua orang untuk membaca dan menulis (sesuaikan sesuai kebutuhan)
CREATE POLICY "Enable read access for all users" ON public.visitor_logs
    FOR SELECT USING (true);

CREATE POLICY "Enable insert access for all users" ON public.visitor_logs
    FOR INSERT WITH CHECK (true);
